### ISSUE TITLE
tf2.3上面无法运行

### ISSUE THREAD

**Issue by bestpredicts** [bojone/keras_adversarial_training#2]
自己改了一下  没成功了   一些model类的api改名了 一些是直接取消了比如model.total_loss。

**Comment by bojone** [comment]
这个是给keras用的，不是给tf.keras用的。keras根本就没法在tf2.3很好地跑起来。

**Comment by bestpredicts** [comment]
嗯嗯 主要是colab上面tf2只提供tf2.3版本的原因  我再试着看看能不能把代码迁移到2.3到环境跑起来
